PW_Online_Shop/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('landing.urls')),
    path('catalogues/',include('catalogues.urls')),
    path('transaksi/',include('transaksi.urls')),
    path('review/',include('review.urls')),
    path('coupon/', include('coupon.urls')),
    path('auth/', include('authentication.urls')),
    path('', include('social_django.urls', namespace='social'))
]

authentication/urls.py
import django.contrib.auth
from django.urls import path, include
from . import views

app_name = 'authentication'

urlpatterns = [
    path('login/', views.login_views, name='login'),
    path('signup/', views.sign_up_views, name='signup'),
    path('logout/', views.logout_views, name='logout'),
]

coupon/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.coupon_page, name ='coupon_page'),
]

authentication/models.py
from django.db import models

# Create your models here.

authentication/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class ModifiedRegistrationForm(UserCreationForm):
    email = forms.EmailField(required = True)

    # hold anything that isnt a form field (meta data)
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2')

    def save(self, commit = True):
        # save(commit = T/F) means save or dont save yet
        # calls the super method of this class (UserCreationForm) and calling it's save method with input as false
        user = super(ModifiedRegistrationForm, self).save(commit = False)
        # cleaned_data makes things save to put in data base
        user.email = self.cleaned_data['email']

        if commit:
            user.save()

        return user

authentication/views.py
from django.shortcuts import render, redirect
from django.contrib import messages

from .forms import ModifiedRegistrationForm
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout


# Create your views here.
def login_views(request):
    '''
    fungsi buat login
    '''
    if request.user.is_authenticated:
        return redirect('/')

    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('landing:landing')
    else:
        form = AuthenticationForm()

    return render(request, 'authentication/login.html', {'form':form})


def sign_up_views(request):
    if request.user.is_authenticated:
        return redirect('/')

    if request.method == 'POST':
        '''
        fungsi buat sign up
        '''
        form = ModifiedRegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('authentication:login')
    else:
        form = ModifiedRegistrationForm()

    return render(request, 'authentication/signup.html', {'form':form})


def logout_views(request):
    '''
    fungsi buat logout
    '''
    logout(request)
    return redirect('/')

authentication/templates/authentication/login.html
<!DOCTYPE html>

{% extends 'base.html' %}

{% load static %}

{% load crispy_forms_tags %}

{% block title %}Login | Toko Online PW{% endblock %}

{% block style %}
    <link rel="stylesheet" href="{% static 'authentication/login.css' %}">
{% endblock %}

{% block content %}
{% include 'navbar.html' %}

<section id="title-section" class="text-center">
    <h3>Login Page</h3>
</section>

<section id="form-section" class="text-center">
    <form method="POST" action="/auth/login/">
        {% csrf_token %}
        <div id="input-section">
            {% for field in form %}
            <span><p class="errors">{{ field.errors }}</p></span>
            <p class="text-left">{{ field.label_tag }} <br></p>
            <span class="">{{ field }}</span>
            {% if field.help_text %}
            <p class="help">{{ field.help_text|safe }}</p>
            {% endif %}
        {% endfor %}
        </div>
        <button type="submit" class="btn btn-success button" name="login">Login</button>
    </form>

    <h5>login with <a href="{% url 'social:begin' 'google-oauth2' %}">google</a>, or <a href="{% url 'authentication:signup' %}">sign up</a> manually</h5>
</section>

{% endblock %}

authentication/templates/authentication/signup.html
<!DOCTYPE html>

{% extends 'base.html' %}

{% load static %}

{% load crispy_forms_tags %}

{% block title %}Sign Up | Toko Online PW{% endblock %}

{% block style %}
    <link rel="stylesheet" href="{% static 'authentication/signup.css' %}">
{% endblock %}

{% block content %}
{% include 'navbar.html' %}

<section id="title-section" class="text-center">
    <h3>Sign Up Page</h3>
</section>

<section id="form-section" class="text-center">
    <form method="POST" action="/auth/signup/">
        {% csrf_token %}
        <div id="input-section">
            {% for field in form %}
            <span><p class="errors">{{ field.errors }}</p></span>
            <p class="text-left">{{ field.label_tag }} <br></p>
            <span class="">{{ field }}</span>
        {% endfor %}
        </div>
        <button type="submit" class="btn btn-success button" name="signup">Login</button>
    </form>
</section>

{% endblock %}