PW_Online_Shop/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('landing.urls')),
    path('catalogues/',include('catalogues.urls')),
    path('transaksi/',include('transaksi.urls')),
    path('review/',include('review.urls')),
    path('coupon/', include('coupon.urls')),
    path('auth/', include('authentication.urls')),
    path('', include('social_django.urls', namespace='social'))
]

authentication/urls.py
import django.contrib.auth
from django.urls import path, include
from . import views

app_name = 'authentication'

urlpatterns = [
    path('login/', views.login_views, name='login'),
    path('signup/', views.sign_up_views, name='signup'),
    path('logout/', views.logout_views, name='logout'),
]

coupon/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.coupon_page, name ='coupon_page'),
]

landing/urls.py
from django.urls import path
from . import views

app_name = 'landing'

urlpatterns = [
    path('',views.landing,name='landing'),
]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!----------------------------CSS Bootstrap + Custom-------------------------------------->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <!--------------------Google Fonts (kalo perlu ditambahin, tambah aja)-------------------->
    <link href="https://fonts.googleapis.com/css?family=Montserrat&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'base.css' %}">
    <!-----------------------------------------Title------------------------------------------>
    <title>{% block title %}{% endblock %}</title>
    {% block style %}{% endblock %}
</head>
<body>
    <!-- {% include 'navbar.html' %} -->

    {% block content %}
    {% endblock %}
    <!-------------------------------------Scripts-------------------------------------------->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    {% block script %}{% endblock %}
</body>
</html>

templates/navbar.html
<!DOCTYPE html>

<style>
    nav {
        width: 100vw;
    }
    
    strong {
        font-weight: 800;
    }

    nav > a > strong {
        color: #DFDFDF;
        font-family: 'Montserrat';
        font-size: 1.75rem;
    }

    .nav-item > strong {
        color: #DFDFDF;
        font-family: 'Montserrat';
    }

    .navbar-nav {
        padding: 0 1vw 0 0;
    }

</style>

<nav class="navbar sticky-top navbar-expand-md navbar-light px-4 py-3" style="background: #2F3A80;">
    <a class="navbar-brand" href="{% url 'landing:landing' %}"><strong>PW's Hobby Shop</strong></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav mr-auto"></div>
    <div class="navbar-nav">
        <a class="nav-item nav-link ml-3" href="{% url 'catalogues' %}"><strong>Catalogues</strong></a>
        <a class="nav-item nav-link ml-3" href="{% url 'coupon_page' %}"><strong>Coupons</strong></a>
        <a class="nav-item nav-link ml-3" href="{% url 'recent-trans' %}"><strong>History</strong></a>
        <a class="nav-item nav-link ml-3" href=""><strong>Categories</strong></a>
        <a class="nav-item nav-link ml-3" href=""><strong>|</strong></a>
        {% if not request.user.is_authenticated %}
            <a class="nav-item nav-link ml-3" href="{% url 'authentication:login' %}"><strong>Login</strong></a>
        {% else %}
            {% if not request.user.first_name == '' %}
                {% if not request.user.last_name == '' %}
                    <a class="nav-item nav-link ml-3" href=""><strong>{{ request.user.first_name }} {{ request.user.last_name }}</strong></a>
                    <a class="nav-item nav-link" href="{% url 'authentication:logout' %}"><strong>Logout</strong></a>
                {% else %}
                    <a class="nav-item nav-link ml-3" href=""><strong>{{ request.user.first_name }}</strong></a>
                    <a class="nav-item nav-link" href="{% url 'authentication:logout' %}"><strong>Logout</strong></a>
                {% endif %}
            {% else %}
                <a class="nav-item nav-link ml-3" href="" id="LoggedName"><strong>{{ request.user.username }}</strong></a>
                <a class="nav-item nav-link" href="{% url 'authentication:logout' %}"><strong>Logout</strong></a>
            {% endif %}
        {% endif %}
    </div>
  </div>
</nav>